package com.osen.osenshop.payment_config;

import com.fasterxml.jackson.annotation.JsonProperty;

public record PaymentRequest(
        @JsonProperty("transaction_amount") Double transactionAmount,
        String token,          // card token generated by Angular
        String description,
        Integer installments,
        @JsonProperty("payment_method_id") String paymentMethodId,
        @JsonProperty("issuer_id") String issuerId,
        Payer payer

) {

public record Payer(
    String email
)
{ }
}
